### ISSUE TITLE
Install fails on Windows with Python 2.7.10

### ISSUE THREAD

**Issue by highlyunavailable** [jakm/txmsgpackrpc#4]
I'm unable to install txmsgpackrpc 1.1 using Python 2.7.10 because of the following error:

```
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\me\appdata\local\temp\pip-build-sxrjzo\txmsgpackrpc\setup.py", line 12, in <module>
        os.link(setup_path, linked_path)
    AttributeError: 'module' object has no attribute 'link'
```

Works fine in 3.5, though.
